<a href="https://colab.research.google.com/github/hansuho113/SwUniv_CancerAnalysis/blob/main/TCGA_CDR_Dohyeon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

In [ ]:
import pandas as pd
import numpy as np

Table sheet 4번째

In [ ]:
# CDR 엑셀에서 table4 PH assumtion 엑셀시트 open
CDR_T4 = pd.read_excel('/content/drive/MyDrive/SW21/TCGA-CDR-SupplementalTableS1.xlsx', sheet_name = 'Table4_PHAssumptionTests')
CDR_T4

         Type  ...                                         Unnamed: 9
0         ACC  ...                                                NaN
1        BLCA  ...                                                NaN
2        BRCA  ...                                                NaN
3        CESC  ...                                             Notes:
4        CHOL  ...  column G is the p-value of testing the proport...
5        COAD  ...  column H is the FDR adjusted p-value of column G.
6        DLBC  ...    p-values or FDR-values < 0.05 are shown in red.
7        ESCA  ...                                                NaN
8         GBM  ...                                                NaN
9        HNSC  ...                                                NaN
10       KICH  ...                                                NaN
11       KIRC  ...                                                NaN
12       KIRP  ...                                                NaN
13        LGG  ...                                                NaN
14       LIHC  ...                                                NaN
15       LUAD  ...                                                NaN
16       LUSC  ...                                                NaN
17       MESO  ...                                                NaN
18         OV  ...                                                NaN
19       PAAD  ...                                                NaN
20       PCPG  ...                                                NaN
21       PRAD  ...                                                NaN
22       READ  ...                                                NaN
23       SARC  ...                                                NaN
24       STAD  ...                                                NaN
25       TGCT  ...                                                NaN
26       THCA  ...                                                NaN
27       UCEC  ...                                                NaN
28        UCS  ...                                                NaN
29  PanCancer  ...                                                NaN

[30 rows x 10 columns]

In [ ]:
CDR_T4.drop(['Unnamed: 8','Unnamed: 9'], axis = 1, inplace = True)
CDR_T4.columns

Index(['Type', 'n', 'Disease_free', 'event_DF', 'With_disease', 'event_WD',
       'p_assumption_test', 'FDR of p_assumption_test'],
      dtype='object')

In [ ]:
CDR_T4_c = CDR_T4[CDR_T4['Type']=='COAD']
CDR_T4_c

   Type    n  ...  p_assumption_test  FDR of p_assumption_test
5  COAD  459  ...              0.748                     0.948

[1 rows x 8 columns]

Table sheet 5번째

In [ ]:
CDR_T5 = pd.read_excel('/content/drive/MyDrive/SW21/TCGA-CDR-SupplementalTableS1.xlsx', sheet_name = 'Table5_PHAssumptionTests', header = 1)
CDR_T5

    type  ...                                        Unnamed: 19
0   BLCA  ...                                                NaN
1   BLCA  ...                                             Notes:
2   BLCA  ...                                 For each endpoint:
3   BRCA  ...   P_assumption_test is the p value of testing t...
4   BRCA  ...  FDR of p_assumption_test is FDR adjusted p val...
5   BRCA  ...    P-values or FDR-values < 0.05 are shown in red.
6   CESC  ...                                                NaN
7   CESC  ...                                                NaN
8   CESC  ...                                                NaN
9   COAD  ...                                                NaN
10  COAD  ...                                                NaN
11  COAD  ...                                                NaN
12   GBM  ...                                                NaN
13   GBM  ...                                                NaN
14   GBM  ...                                                NaN
15  HNSC  ...                                                NaN
16  HNSC  ...                                                NaN
17  HNSC  ...                                                NaN
18  KIRC  ...                                                NaN
19  KIRC  ...                                                NaN
20  KIRC  ...                                                NaN
21   LGG  ...                                                NaN
22   LGG  ...                                                NaN
23   LGG  ...                                                NaN
24    OV  ...                                                NaN
25    OV  ...                                                NaN
26    OV  ...                                                NaN
27  PRAD  ...                                                NaN
28  PRAD  ...                                                NaN
29  PRAD  ...                                                NaN
30  SKCM  ...                                                NaN
31  SKCM  ...                                                NaN
32  SKCM  ...                                                NaN
33  STAD  ...                                                NaN
34  STAD  ...                                                NaN
35  STAD  ...                                                NaN
36  THCA  ...                                                NaN
37  THCA  ...                                                NaN
38  THCA  ...                                                NaN
39  UCEC  ...                                                NaN
40  UCEC  ...                                                NaN
41  UCEC  ...                                                NaN

[42 rows x 20 columns]

In [ ]:
CDR_T5.drop(['Unnamed: 18','Unnamed: 19'], axis = 1, inplace = True)
CDR_T5.columns

Index(['type', 'site', 'num', 'event', 'p_assumption_test',
       'FDR of p_assumption_test', 'num.1', 'event.1', 'p_assumption_test.1',
       'FDR of p_assumption_test.1', 'num.2', 'event.2', 'p_assumption_test.2',
       'FDR of p_assumption_test.2', 'num.3', 'event.3', 'p_assumption_test.3',
       'FDR of p_assumption_test.3'],
      dtype='object')

In [ ]:
CDR_T5_c = CDR_T5[CDR_T5['type']=='COAD']
CDR_T5_c
# num부터 FDR까지가 한 묶음으로 순서대로 OS, PFI, DFI, DSS

    type    site  num  ...  event.3  p_assumption_test.3  FDR of p_assumption_test.3
9   COAD     1st  173  ...       28                0.025                         0.1
10  COAD     2nd   52  ...        6                  NaN                         NaN
11  COAD  Others  233  ...       30                  NaN                         NaN

[3 rows x 18 columns]

Table sheet 6번째

In [ ]:
CDR_TSS = pd.read_excel('/content/drive/MyDrive/SW21/TCGA-CDR-SupplementalTableS1.xlsx', sheet_name = 'TSS_Info', header = 2)
CDR_TSS

    TSS Code  ...                                       Disease type
0         01  ...                  Ovarian serous cystadenocarcinoma
1         02  ...                            Glioblastoma multiforme
2         04  ...                  Ovarian serous cystadenocarcinoma
3         05  ...                                Lung adenocarcinoma
4         06  ...                            Glioblastoma multiforme
..       ...  ...                                                ...
825       ZS  ...                     Liver hepatocellular carcinoma
826       ZT  ...                                            Thymoma
827       ZU  ...                                 Cholangiocarcinoma
828       ZW  ...                          Pancreatic adenocarcinoma
829       ZX  ...  Cervical squamous cell carcinoma and endocervi...

[830 rows x 3 columns]

In [ ]:
CDR_TSS_sort = CDR_TSS.sort_values(by = 'Disease type')
CDR_TSS_sort

    TSS Code                  Source Site            Disease type
372       GP                  MD Anderson  Acute Myeloid Leukemia
565       PH           Gundersen Lutheran  Acute Myeloid Leukemia
577       Q4             Emory University  Acute Myeloid Leukemia
779       Y3     University of New Mexico  Acute Myeloid Leukemia
182       AB        Washington University  Acute Myeloid Leukemia
..       ...                          ...                     ...
117       5H   Retina Consultants Houston          Uveal Melanoma
694       V3  Cleveland Clinic Foundation          Uveal Melanoma
695       V4               Institut Curie          Uveal Melanoma
797       YV                        MSKCC          Uveal Melanoma
626       RZ          Wills Eye Institute          Uveal Melanoma

[830 rows x 3 columns]

In [ ]:
grouped = CDR_TSS_sort.groupby('Disease type')
for name, group in grouped:
  print("groupname: ", name)

groupname:  Acute Myeloid Leukemia
groupname:  Adrenocortical carcinoma
groupname:  Bladder Urothelial Carcinoma
groupname:  Brain Lower Grade Glioma
groupname:  Breast invasive carcinoma
groupname:  Cell Line Control
groupname:  Cervical squamous cell carcinoma and endocervical adenocarcinoma
groupname:  Cholangiocarcinoma
groupname:  Chronic Myelogenous Leukemia
groupname:  Colon adenocarcinoma
groupname:  Esophageal carcinoma
groupname:  Glioblastoma multiforme
groupname:  Head and Neck squamous cell carcinoma
groupname:  Kidney Chromophobe
groupname:  Kidney renal clear cell carcinoma
groupname:  Kidney renal papillary cell carcinoma
groupname:  Liver hepatocellular carcinoma
groupname:  Lung adenocarcinoma
groupname:  Lung squamous cell carcinoma
groupname:  Lymphoid Neoplasm Diffuse Large B-cell Lymphoma
groupname:  Mesothelioma
groupname:  Miscellaneous
groupname:  Ovarian serous cystadenocarcinoma
groupname:  Pancreatic adenocarcinoma
groupname:  Pheochromocytoma and Paraganglioma
groupname:  Prostate adenocarcinoma
groupname:  Rectum adenocarcinoma
groupname:  Sarcoma
groupname:  Skin Cutaneous Melanoma
groupname:  Stomach adenocarcinoma
groupname:  Testicular Germ Cell Tumors
groupname:  Thymoma
groupname:  Thyroid carcinoma
groupname:  Uterine Carcinosarcoma
groupname:  Uterine Corpus Endometrial Carcinoma
groupname:  Uveal Melanoma

# Disease type



*   Acute myeloid leukemia : 급성 골수성 백혈병
*   Adrenocortical carcinoma : 부신우연종
*   Bladder urothelial carcinoma : 요로상피세포암
*   Brain lower grade glioma : 뇌 저등급 신경교종
*   Breast invasive carcinoma : 유방암
*   Cell line control
* Cervical squamous cell carcinoma and endocervical
* adenocarcinoma : 자궁경부암
* Cholangiocarcinoma : 쓸개암
* Chronic Myelogenous Leukemia : 만성 골수성 백혈병
* Colon adenocarcinoma : 대장암
* Esophageal carcinoma : 식도암
* Glioblastoma multiforme : 교모세포종
* Head and Neck squamous cell carcinoma : 두경부 편평세포암 종
* Kidney Chromophobe : 신세포암
* Kidney renal clear cell carcinoma :  신세포암
* Kidney renal papillary cell carcinoma : 신세포암
* Liver hepatocellular carcinoma :  간세포암
* Lung adenocarcinoma : 폐 선암
* Lung squamous cell carcinoma : 비세포성폐암
* Lymphoid Neoplasm Diffuse Large B-cell Lymphoma : 림프계종양
* Mesothelioma : 악성중피종
* Miscellaneous : 복합
* Ovarian serous cystadenocarcinoma : 경계영역성 난소종양
* Pancreatic adenocarcinoma : 췌장암
* Pheochromocytoma and Paraganglioma : 갈색세포종과 복부부신 경절종
* Prostate adenocarcinoma :  전립선암
* Rectum adenocarcinoma : 직장암
* Sarcoma : 암 육종
* Skin Cutaneous Melanoma : 피부흑색종
* Stomach adenocarcinoma : 위암
* Testicular Germ Cell Tumors : 생식세포암 고환암
* Thymoma :  흉선종
* Thyroid carcinoma : 갑상선암
* Uterine Carcinosarcoma : 자궁내막암
* Uterine Corpus Endometrial Carcinoma : 자궁내막샘암종
* Uveal Melanoma : 포도막(맥락막) 흑색종

In [ ]:
CDR_TSS_c = CDR_TSS_sort[CDR_TSS_sort['Disease type'] == 'Colon adenocarcinoma']
CDR_TSS_c.sort_index()
# 대장암의 TSS code 알아냄

    TSS Code  ...          Disease type
63        3L  ...  Colon adenocarcinoma
91        4N  ...  Colon adenocarcinoma
96        4T  ...  Colon adenocarcinoma
121       5M  ...  Colon adenocarcinoma
178       A6  ...  Colon adenocarcinoma
181       AA  ...  Colon adenocarcinoma
184       AD  ...  Colon adenocarcinoma
191       AM  ...  Colon adenocarcinoma
199       AU  ...  Colon adenocarcinoma
203       AY  ...  Colon adenocarcinoma
204       AZ  ...  Colon adenocarcinoma
237       CA  ...  Colon adenocarcinoma
247       CK  ...  Colon adenocarcinoma
249       CM  ...  Colon adenocarcinoma
261       D5  ...  Colon adenocarcinoma
277       DM  ...  Colon adenocarcinoma
322       F4  ...  Colon adenocarcinoma
354       G4  ...  Colon adenocarcinoma
529       NH  ...  Colon adenocarcinoma
584       QG  ...  Colon adenocarcinoma
588       QL  ...  Colon adenocarcinoma
598       R1  ...  Colon adenocarcinoma
621       RU  ...  Colon adenocarcinoma
644       SK  ...  Colon adenocarcinoma
651       SS  ...  Colon adenocarcinoma
662       T9  ...  Colon adenocarcinoma
706       VK  ...  Colon adenocarcinoma
743       WS  ...  Colon adenocarcinoma
745       WU  ...  Colon adenocarcinoma

[29 rows x 3 columns]

# TCGA 바코드 구조
https://m.blog.naver.com/PostView.nhn?blogId=cjh226&logNo=220992617831&proxyReferer=https:%2F%2Fwww.google.com%2F

TCGA-01-0001 = TCGA-TSS code-참여자

Table sheet 7번째

In [ ]:
CDR_T7 = pd.read_excel('/content/drive/MyDrive/SW21/TCGA-CDR-SupplementalTableS1.xlsx', sheet_name = 'Fig2EFG_AdditionalInfo', header = 2)
CDR_T7

                                           Unnamed: 0  ... Unnamed: 33
0                                                 ACC  ...    0.071413
1                                                BLCA  ...    0.017964
2                                                COAD  ...   -0.000581
3                                                ESCA  ...    0.277417
4                                                HNSC  ...    0.020876
5                                                KIRC  ...    0.035099
6                                                KIRP  ...   -0.010618
7                                                LUAD  ...    0.091634
8                                                LUSC  ...   -0.025549
9                                                MESO  ...   -0.018298
10                                               PAAD  ...   -0.070498
11                                               SKCM  ...    0.107848
12                                               STAD  ...    0.043716
13                                                UVM  ...   -0.023343
14                                                NaN  ...         NaN
15                                             Notes:  ...         NaN
16  Proportional hazards assumption tests: p_value...  ...         NaN
17  Cox Models: Green color shows logHRs of high s...  ...         NaN
18                                                NaN  ...         NaN

[19 rows x 34 columns]

In [ ]:
CDR_T7.drop([14, 15, 16, 17, 18], inplace=True)
CDR_T7

   Unnamed: 0      p_value       FDR  ...  95%CI.HR.4  Unnamed: 32  Unnamed: 33
0         ACC     0.325162  0.443116  ...   3.4-17.36     0.102238     0.071413
1        BLCA     0.348162  0.443116  ...   1.54-3.74     0.069815     0.017964
2        COAD   0.00881358  0.041130  ...  3.19-11.34     0.029464    -0.000581
3        ESCA     0.838839  0.838839  ...   2.47-8.76     0.072862     0.277417
4        HNSC     0.685191  0.753344  ...   1.26-3.81     0.064064     0.020876
5        KIRC  3.53651e-06  0.000050  ...  5.79-15.69     0.084312     0.035099
6        KIRP  0.000279109  0.001954  ...   9.9-170.4    -0.017431    -0.010618
7        LUAD     0.236867  0.414517  ...   1.51-3.33     0.188016     0.091634
8        LUSC     0.292132  0.443116  ...    1.7-4.24     0.039078    -0.025549
9        MESO     0.189406  0.386850  ...   0.43-1.67     0.118307    -0.018298
10       PAAD      0.10674  0.298873  ...   0.63-2.62    -0.116212    -0.070498
11       SKCM    0.0640707  0.224248  ...   1.05-1.92     0.106085     0.107848
12       STAD     0.699534  0.753344  ...   1.54-3.72     0.110469     0.043716
13        UVM     0.193425  0.386850  ...   0.69-3.94    -0.022008    -0.023343

[14 rows x 34 columns]

In [ ]:
CDR_T7 = CDR_T7.rename(columns={'Unnamed: 0' : 'type', 'Unnamed: 32' : 'PFI.logHR.diff', 'Unnamed: 33' : 'DSS.logHR.diff'})
CDR_T7

    type      p_value       FDR  ...  95%CI.HR.4  PFI.logHR.diff  DSS.logHR.diff
0    ACC     0.325162  0.443116  ...   3.4-17.36        0.102238        0.071413
1   BLCA     0.348162  0.443116  ...   1.54-3.74        0.069815        0.017964
2   COAD   0.00881358  0.041130  ...  3.19-11.34        0.029464       -0.000581
3   ESCA     0.838839  0.838839  ...   2.47-8.76        0.072862        0.277417
4   HNSC     0.685191  0.753344  ...   1.26-3.81        0.064064        0.020876
5   KIRC  3.53651e-06  0.000050  ...  5.79-15.69        0.084312        0.035099
6   KIRP  0.000279109  0.001954  ...   9.9-170.4       -0.017431       -0.010618
7   LUAD     0.236867  0.414517  ...   1.51-3.33        0.188016        0.091634
8   LUSC     0.292132  0.443116  ...    1.7-4.24        0.039078       -0.025549
9   MESO     0.189406  0.386850  ...   0.43-1.67        0.118307       -0.018298
10  PAAD      0.10674  0.298873  ...   0.63-2.62       -0.116212       -0.070498
11  SKCM    0.0640707  0.224248  ...   1.05-1.92        0.106085        0.107848
12  STAD     0.699534  0.753344  ...   1.54-3.72        0.110469        0.043716
13   UVM     0.193425  0.386850  ...   0.69-3.94       -0.022008       -0.023343

[14 rows x 34 columns]

In [ ]:
CDR_T7_c = CDR_T7[CDR_T7['type']=='COAD']
CDR_T7_c

   type     p_value      FDR  ...  95%CI.HR.4  PFI.logHR.diff  DSS.logHR.diff
2  COAD  0.00881358  0.04113  ...  3.19-11.34        0.029464       -0.000581

[1 rows x 34 columns]

table 7의 경우 논문을 읽어봐야지 조금 이해가 될 것 같음

Table sheet 1번째

In [ ]:
CDR_T1 = pd.read_excel('/content/drive/MyDrive/SW21/TCGA-CDR-SupplementalTableS1.xlsx', index_col = 0)
CDR_T1

      bcr_patient_barcode type  ...  PFI.time Redaction
1            TCGA-OR-A5J1  ACC  ...     754.0       NaN
2            TCGA-OR-A5J2  ACC  ...     289.0       NaN
3            TCGA-OR-A5J3  ACC  ...      53.0       NaN
4            TCGA-OR-A5J4  ACC  ...     126.0       NaN
5            TCGA-OR-A5J5  ACC  ...      50.0       NaN
...                   ...  ...  ...       ...       ...
11156        TCGA-YZ-A980  UVM  ...    1556.0       NaN
11157        TCGA-YZ-A982  UVM  ...     495.0       NaN
11158        TCGA-YZ-A983  UVM  ...     798.0       NaN
11159        TCGA-YZ-A984  UVM  ...     154.0       NaN
11160        TCGA-YZ-A985  UVM  ...    1184.0       NaN

[11160 rows x 33 columns]

In [ ]:
CDR_COAD = CDR_T1[CDR_T1['type'] == 'COAD']
CDR_COAD

     bcr_patient_barcode  type  ...  PFI.time Redaction
1954        TCGA-3L-AA1B  COAD  ...     475.0       NaN
1955        TCGA-4N-A93T  COAD  ...     146.0       NaN
1956        TCGA-4T-AA8H  COAD  ...     385.0       NaN
1957        TCGA-5M-AAT4  COAD  ...      49.0       NaN
1958        TCGA-5M-AAT6  COAD  ...     219.0       NaN
...                  ...   ...  ...       ...       ...
2408        TCGA-QL-A97D  COAD  ...     666.0       NaN
2409        TCGA-RU-A8FL  COAD  ...     256.0       NaN
2410        TCGA-SS-A7HO  COAD  ...     506.0       NaN
2411        TCGA-T9-A92H  COAD  ...      81.0       NaN
2412        TCGA-WS-AB45  COAD  ...    2130.0       NaN

[459 rows x 33 columns]

In [ ]:
# 치료결과를 기준으로 그룹핑함
group_response = CDR_COAD.groupby('treatment_outcome_first_course')
for name, group in group_response:
  print("groupname: ", name)

groupname:  Complete Remission/Response
groupname:  Partial Remission/Response
groupname:  Progressive Disease
groupname:  Stable Disease
groupname:  [Discrepancy]
groupname:  [Not Applicable]
groupname:  [Not Available]
groupname:  [Unknown]

치료 결과에 대한 말들이 제각기라서 통일되게 묶어야 할 것 같음

In [ ]:
group_LD = CDR_COAD.groupby('vital_status')
for name, group in group_LD:
  print("groupname : ", name)
  print("groupdata: ")
  print(group)
  # 생존 357 사망 102

groupname :  Alive
groupdata:
     bcr_patient_barcode  type  ...  PFI.time Redaction
1954        TCGA-3L-AA1B  COAD  ...     475.0       NaN
1955        TCGA-4N-A93T  COAD  ...     146.0       NaN
1956        TCGA-4T-AA8H  COAD  ...     385.0       NaN
1959        TCGA-5M-AATE  COAD  ...     810.0       NaN
1960        TCGA-A6-2670  COAD  ...     775.0  Redacted
...                  ...   ...  ...       ...       ...
2408        TCGA-QL-A97D  COAD  ...     666.0       NaN
2409        TCGA-RU-A8FL  COAD  ...     256.0       NaN
2410        TCGA-SS-A7HO  COAD  ...     506.0       NaN
2411        TCGA-T9-A92H  COAD  ...      81.0       NaN
2412        TCGA-WS-AB45  COAD  ...    2130.0       NaN

[357 rows x 33 columns]
groupname :  Dead
groupdata:
     bcr_patient_barcode  type  ...  PFI.time Redaction
1957        TCGA-5M-AAT4  COAD  ...      49.0       NaN
1958        TCGA-5M-AAT6  COAD  ...     219.0       NaN
1961        TCGA-A6-2671  COAD  ...     535.0       NaN
1965        TCGA-A6-2676  COAD  ...    1305.0       NaN
1966        TCGA-A6-2677  COAD  ...     740.0       NaN
...                  ...   ...  ...       ...       ...
2391        TCGA-G4-6626  COAD  ...    1422.0       NaN
2395        TCGA-NH-A50U  COAD  ...     276.0       NaN
2398        TCGA-NH-A6GA  COAD  ...       6.0       NaN
2402        TCGA-NH-A8F8  COAD  ...     511.0       NaN
2406        TCGA-QG-A5Z1  COAD  ...     256.0       NaN

[102 rows x 33 columns]